# SELECT
#     D.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
# FROM
#     (SELECT
#         B.AUTHOR_ID, B.CATEGORY, A.TOTAL * B.PRICE AS TOTAL_SALES
#     FROM
#         (SELECT
#             BOOK_ID, SUM(SALES) TOTAL
#         FROM
#             BOOK_SALES
#         WHERE
#             YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
#         GROUP BY
#             BOOK_ID) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID) C JOIN AUTHOR D ON C.AUTHOR_ID = D.AUTHOR_ID
# ORDER BY
#     D.AUTHOR_ID ASC, C.CATEGORY DESC
SELECT
    D.AUTHOR_ID, 
    D.AUTHOR_NAME, 
    C.CATEGORY, 
    SUM(C.TOTAL_SALES) AS TOTAL_SALES
FROM
    (SELECT
        B.AUTHOR_ID, 
        B.CATEGORY, 
        SUM(A.TOTAL) * B.PRICE AS TOTAL_SALES
    FROM
        (SELECT
            BOOK_ID, 
            SUM(SALES) AS TOTAL
        FROM
            BOOK_SALES
        WHERE
            YEAR(SALES_DATE) = 2022 
            AND MONTH(SALES_DATE) = 1
        GROUP BY
            BOOK_ID) A
    JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
    GROUP BY
        B.AUTHOR_ID, B.CATEGORY, B.PRICE) C
JOIN AUTHOR D ON C.AUTHOR_ID = D.AUTHOR_ID
GROUP BY
    D.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY
ORDER BY
    D.AUTHOR_ID ASC, C.CATEGORY DESC;
