WITH BEST AS (
    SELECT
        FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM 
        REST_INFO
    GROUP BY
        FOOD_TYPE
)
SELECT
    R.FOOD_TYPE, REST_ID, REST_NAME, B.FAVORITES
FROM
    BEST B JOIN REST_INFO R ON (R.FAVORITES = B.FAVORITES AND R.FOOD_TYPE = B.FOOD_TYPE)
ORDER BY
    R.FOOD_TYPE DESC