-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M, REST_REVIEW R
WHERE M.MEMBER_ID = (SELECT R2.MEMBER_ID
                        FROM REST_REVIEW R2
                    GROUP BY R2.MEMBER_ID
                    ORDER BY COUNT(*) DESC LIMIT 1)
     AND M.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;