# WITH CAR AS (
#     SELECT DISTINCT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# )
# SELECT
#     C.CAR_ID,
#     CASE 
#         WHEN EXISTS (
#             SELECT 1 
#             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#             WHERE H.CAR_ID = C.CAR_ID 
#             AND H.START_DATE <= '2022-10-16' 
#             AND H.END_DATE >= '2022-10-16'
#         ) THEN '대여중'
#         ELSE '대여 가능'
#     END AS AVAILABILITY
# FROM
#     CAR C
# ORDER BY
#     C.CAR_ID DESC

SELECT
    C.CAR_ID,
    CASE
        WHEN H.START_DATE IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM
    (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) C 
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    ON (C.CAR_ID = H.CAR_ID AND H.START_DATE <= '2022-10-16' AND H.END_DATE >= '2022-10-16')
ORDER BY
    C.CAR_ID DESC