SELECT 
    B.USER_ID, B.NICKNAME, A.TOTAL_SALES
FROM
    (SELECT
        WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM(PRICE) >= 700000) A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY
    A.TOTAL_SALES ASC