WITH CAR_RENTAL AS (
SELECT
    CAR_ID, MONTH(START_DATE)
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
),
CAR_COUNT AS (
SELECT
    CAR_ID
FROM
    CAR_RENTAL
GROUP BY
    CAR_ID
HAVING
    COUNT(*) >= 5
)
SELECT
    MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN (SELECT CAR_ID FROM CAR_COUNT)
    AND START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY
    MONTH(START_DATE), CAR_ID
ORDER BY
    MONTH(START_DATE), CAR_ID DESC
    