SELECT B.CATEGORY, SUM(A.TOTAL_SALES) TOTAL_SALES
FROM 
    (SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY